version: "3.9"
services:
  server:
    image: "pandologic-server:nadar"
    ports:
      - 5000:80
      - 5050:443
    depends_on:
      - db.mssql.server
    restart: on-failure

  client:
    image: "pandologic-client:nadar"
    ports: 
      - 3000:3000
    environment:
      REACT_APP_ENV: "development"
    depends_on:
      - server
    restart: on-failure
      
  db.mssql.server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Password@12345"
      ACCEPT_EULA: "Y"
    