version: "3.9"
services:
  server:
    image: pandologic-server: nadar
    ports: 5000:5000

  client:
    image: pandologic-client:nadar
    ports: 3000:3000
    depends_on: server

  sql_client:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=sysadmin123
    